### ISSUE TITLE
Only 19 lines?

### ISSUE THREAD

**Issue by CHonesetDoPa** [thebuster0/MotionASCII#1]
I means...... It's too small.

**Comment by thebuster0** [comment]
No, it’s still in the pseudo-code stage, I’ll upload the code in a few days.

**Comment by CHonesetDoPa** [comment]
......Maybe use Workerman instead of Python(

**Comment by thebuster0** [comment]
There is currently no incentive to rewrite this project in PHP nor its related frameworks, as the project's intention isn't about writing a webapp, it's a console app.

**Comment by CHonesetDoPa** [comment]
But workerman is like node.js,hhh(

**Comment by thebuster0** [comment]
I do acknowledge that Workerman is similar to Node.JS in some way. But again, as stated before, there is no incentive to rewrite this project in JavaScript nor PHP nor in other programming languages.
